// Code generated by "stringer -type=OpCode"; DO NOT EDIT

package buddybot

import "fmt"

const _OpCode_name = "InvalidOpRegisterOpUnregisterOpMessageOpRawMessageOpDirectMessageOpNoticeOpJoinOpNickOpPingOpClientListOpDisconnectOpNoOp"

var _OpCode_index = [...]uint8{0, 9, 19, 31, 40, 52, 67, 75, 81, 87, 93, 105, 117, 121}

func (i OpCode) String() string {
	if i < 0 || i >= OpCode(len(_OpCode_index)-1) {
		return fmt.Sprintf("OpCode(%d)", i)
	}
	return _OpCode_name[_OpCode_index[i]:_OpCode_index[i+1]]
}
