// Code generated by "stringer -type=ConnState"; DO NOT EDIT

package main

import "fmt"

const _ConnState_name = "UnknownConnectedDisconnected"

var _ConnState_index = [...]uint8{0, 7, 16, 28}

func (i ConnState) String() string {
	if i < 0 || i >= ConnState(len(_ConnState_index)-1) {
		return fmt.Sprintf("ConnState(%d)", i)
	}
	return _ConnState_name[_ConnState_index[i]:_ConnState_index[i+1]]
}
